site_name: readme-ai
repo_url: https://github.com/eli64s/readme-ai
site_description: "A tool to generate beautiful README.md files for your projects."

theme:
  icon:
    repo: fontawesome/brands/github-alt
  name: material
  palette:
    primary: "gray"
    accent: "white"
    text: "blue"
    code: "purple"
    link: "blue"
    background: "gray"

nav:
  - Home: index.md
  - Installation and Setup:
      - "Installation": installation.md
      - "Pip": installation.md
      - "Docker": installation.md
      - "From Source": installation.md
  - Quickstart:
      - "Readme-ai CLI": quickstart.md
      - "Readme-ai UI": quickstart.md
  - Examples:
      - "Examples": examples.md
  - Features:
      - "Features": features.md
  - Configuration:
      - "Project Structure": configuration.md
      - "Command Line Arguments": configuration.md
  - Concepts: concepts.md
  - Contributing: contribute.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html

extra_css:
  - css/termynal.css
  - css/custom.css

extra_javascript:
  - js/termynal.js
  - js/custom.js

extra:
  version:
    provider: mike

plugins:
  - mkdocstrings
  - mike:
      version_selector: true
  - search:
