site_name: readme-ai
repo_url: https://github.com/eli64s/readme-ai
site_description: "🎈 Automated README file generator, powered by GPT language model APIs."

theme:
  icon:
    repo: fontawesome/brands/github-alt
  name: material

nav:
  - Home: index.md
  - Installation: installation.md
  - Getting Started:
      - "Prerequisites": prerequisites.md
      - "Running the CLI": cli.md
      - "Streamlit App": streamlit.md
      - "Configuration": configuration.md
  - Features:
      - "Customization": customization.md
      - "Text Summarization": text-summarization.md
      - "Dynamic Content": dynamic-content.md
      - "Templates": templates.md
  - Examples: examples.md
  - Concepts:
      - "Core Concepts": concepts.md
      - "How It Works": how-it-works.md
  - Contributing: contributing.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html

extra_css:
  - css/termynal.css
  - css/custom.css

extra_javascript:
  - js/termynal.js
  - js/custom.js

plugins:
  - search
