[tool.poetry]
name = "readme-ai"
version = "0.0.1"
description = "🚀 Generate awesome README files from the terminal, powered by OpenAI's GPT language model APIs 💫"
authors = ["Eli <43382407+eli64s@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/eli64s/README-AI"
documentation = "https://github.com/eli64s/README-AI/blob/main/README.md"
keywords = [
    "markdown",
    "readme",
    "readme-badges",
    "documentation-generator",
    "markdown-generator",
    "automated-documentation",
    "awesome-readme",
    "readme-generator",
    "python-ai",
    "gpt-3",
    "openai-api",
    "shieldsio-badges",
    "gpt-4",
    "llms",
    "openai-python",
    "chatgpt-python",
    "llmops",
    "openai-chatbot",
    "gpt-35-turbo",
]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.4.0"
black = "21.9b0"
click = "8.0.1"
colorlog = "^6.7.0"
cachetools = "^5.3.1"
dacite = "^1.8.1"
gitpython = "^3.1.31"
httpx = "^0.24.1"
h2 = "^4.1.0"
pre-commit = "2.15.0"
pyyaml = "^6.0"
pytest = "^7.3.2"
pytest-cov = "^4.1.0"
responses = "^0.23.1"
setuptools = "^68.0.0"
tabulate = "^0.9.0"
tenacity = "^8.2.2"
tiktoken = "^0.4.0"
openai = "^0.27.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
readme-ai = "readme_ai.main:main"

# Autoflake
[tool.autoflake]
ignore_pass_statements = true
ignore-pass-after-docstring = true
remove_all_unused_imports = true
recursive = true

# Autopep8
[tool.autopep8]
max-line-length = 88

# Black
[tool.black]
target-version = ["py38", "py39", "py310"]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
      .eggs
    | .git
    | .hg
    | .mypy_cache
    | .pytest_cache
    | .tox
    | venv
    | benchmarks
    | _build
    | buck-out
    | build
    | dist
  )/
'''

# Flake8
[flake8]
max-line-length = 88

# iSort
[tool.isort]
profile = "black"
line_length = 88
lines_after_imports = 2
multi_line_output = 3
include_trailing_comma = true
virtual_env = "conda"

# Pytest
[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
addopts = "--strict-markers --disable-pytest-warnings"

# Pytest Coverage
[tool.coverage.run]
omit = [
    "tests/*",
    "setup.py",
    "*/__init__.py"
]

# Yapf
[tool.yapf]
based_on_style = "google"
column_limit = 88
indent_width = 4
dedent_closing_brackets = true
