# OpenAI
[api]
engine = "text-davinci-003"
key = "<OPENAI-API-KEY>"

# GitHub
[github]
dirs = "src/*.py"
url = "https://github.com/eli64s/PydocsAI"

# Paths
[paths]
badges = "conf/badges.json"
docs = "docs/raw_data.csv"
md = "docs/readme.md"

# Markdown
[md]
head = """\n<div align="center">\n<h1 align="center">
\n<img src="https://raw.githubusercontent.com/PKief/vscode-material-icon-theme/ec559a9f6bfd399b82bb44393651661b08aaf7ba/icons/folder-markdown-open.svg" width="100">
\n<div><p>{}</p></h1>

\n> [insert-project-summary]
\n{}
\n</div>
\n\n---
"""

body = """
\n## Introduction
\n> [insert-description]
\n## Feautres
\n> [insert-description]
"""

modules = """
\n---
\n<img src="https://raw.githubusercontent.com/PKief/vscode-material-icon-theme/ec559a9f6bfd399b82bb44393651661b08aaf7ba/icons/folder-src-open.svg" width="80" />
\n## Modules
"""

tree = """
\n---
\n<img src="https://raw.githubusercontent.com/PKief/vscode-material-icon-theme/ec559a9f6bfd399b82bb44393651661b08aaf7ba/icons/folder-github-open.svg" width="80" />
\n## Repository Structure
"""

usage = """
\n---\n
\n## Getting Started
\n### Prerequisites
\nBefore you begin, ensure that you have the following prerequisites installed:

\n> - [insert-prerequisites-if-needed]

\n### Installation
\n1. Clone the {name} repository:

\n```sh\ngit clone {url} && cd {name}\n```
\n2. Create a new Conda environment and install the required dependencies:
\n```sh\nconda env create -f setup/environment.yaml\nconda activate {name}\n```
\n> 3. [insert-additional-steps]

\n```sh\n #... \n```
\n### Running {name}
\n```sh\n# ... \n```
\n---

\n## Roadmap

\n> - [X] [insert-task]
\n> - [ ] [insert-task]
\n> - [ ] [insert-task]
\n---

\n## Contributing
\n> [insert-description]
\n---

## Acknowledgments
\n> [insert-description]
\n---
"""