# Default configuration file.
defaults:
  - _self_
  - driver: openai
  - repository: github
  - html: tags

html_file: output/structured_doc.html
pkgs_file: conf/data/icons.json
doc_file: output/raw_docs.csv
