# Default configuration file.
defaults:
  - _self_
  - driver: openai
  - html: tags
  - repository: github

doc_file: docs/raw_docs.csv
html_file: docs/html_docs.html
md_file: docs/output.md
pkgs_file: conf/data/icons.json
