# Default configuration file.
defaults:
  - _self_
  - driver: openai
  - html: tags
  - repository: github

docs: docs/raw_docs.csv
html: docs/html_docs.html
mrkd: docs/output.md
pkgs: conf/data/icons.json
