# OpenAI
[api]
engine = "text-davinci-003"
key = "<OPENAI-API-KEY>"

# GitHub
[github]
url = "https://github.com/eli64s/PydocsAI"

# Paths
[paths]
badges = "conf/badges.json"
docs = "docs/gpt/raw_data.csv"
html = "docs/html/readme.html"
md = "docs/markdown/_readme.md"

# HTML
[html]
head = """
<html>
<div>
<img src="https://raw.githubusercontent.com/PKief/vscode-material-icon-theme/ec559a9f6bfd399b82bb44393651661b08aaf7ba/icons/folder-markdown-open.svg" width="80">
"""
body = """
<hr>
<h3 id="overview">Overview</h3>
<p>[insert-description]</p>
<hr>
<h3 id="use-case">Use-Case</h3>
<p>[insert-description]</p>
<hr>
<h3 id="features">Features</h3>
<p>[insert-description]</p>
<hr>
<p><img src="https://raw.githubusercontent.com/PKief/vscode-material-icon-theme/ec559a9f6bfd399b82bb44393651661b08aaf7ba/icons/folder-src-open.svg"
width="80" /></p>
<h3 id="modules">Modules</h3>
<br>
"""
setup = """
<hr>
<h2>Getting Started</h2><p>[insert-description]</p>
<h3>Usage</h3>
<pre><code class="language-Bash"># 1. Clone GitHub repository.
git clone {} &amp;&amp; cd {}
</code></pre>
<h2>Contribute</h2>
<ul>
  <li>Contributions and suggestions welcome!</li>
</ul>
<hr>
</html>
"""
tree = """
<hr>
<p><img
src="https://raw.githubusercontent.com/PKief/vscode-material-icon-theme/ec559a9f6bfd399b82bb44393651661b08aaf7ba/icons/folder-github-open.svg"
width="80" /></p>
<h3 id="repository-structure">Repository Structure</h3>
<br>
"""