# OpenAI
[api]
engine = "text-davinci-003"
key = "<OPENAI-API-KEY>"

# GitHub
[github]
file_type = "src/*.py"
url = "https://github.com/eli64s/PydocsAI"

# Paths
[paths]
badges = "conf/badges.json"
docs = "docs/raw_data.csv"
md = "docs/readme.md"

# Markdown
[md]
head = """\n<div align="center">\n<h1 align="center">
\n<img src="https://raw.githubusercontent.com/PKief/vscode-material-icon-theme/ec559a9f6bfd399b82bb44393651661b08aaf7ba/icons/folder-markdown-open.svg" width="100">
\n<div><p>{}</p></h1>
\n<h3 align="center">[insert-project-summary]</h3>{}
\n</div>
\n\n---
"""

body = """
\n## Overview
\n> [insert-description]
\n## Use-Case
\n> [insert-description]
\n## Feautres
\n> [insert-description]
"""

modules = """
\n---
\n<img src="https://raw.githubusercontent.com/PKief/vscode-material-icon-theme/ec559a9f6bfd399b82bb44393651661b08aaf7ba/icons/folder-src-open.svg" width="80" />
\n## Modules
"""

tree = """
\n---
\n<img src="https://raw.githubusercontent.com/PKief/vscode-material-icon-theme/ec559a9f6bfd399b82bb44393651661b08aaf7ba/icons/folder-github-open.svg" width="80" />
\n## Repository Structure
"""

usage = """
\n---
\n## Getting Started

\n### Usage
\n```Bash\n# 1. Clone GitHub repository.\ngit clone {} && cd {}

\n# 2...

\n# 3...
\n```

\n---

\n## Contribute

\n> [insert-description]

\n## Roadmap

\n> [insert-description]

\n## References

\n> [insert-description]

\n---
"""