# Default configuration file.
defaults:
  - _self_
  - driver: openai
  - repository: github
  - html: tags

doc_file: output/raw_docs.csv
html_file: output/html_docs.html
md_file: output/output.md
pkgs_file: conf/data/icons.json
