# File names of programming language dependency files.

[file_names]
name = [
    'Cargo.lock',
    'Cargo.toml',
    'Gemfile',
    'Gemfile.lock',
    'Pipfile',
    'Pipfile.lock',
    'build.boot',
    'build.boot.repl',
    'build.gradle',
    'build.sbt',
    'build.spoon',
    'composer.json',
    'composer.lock',
    'conda.yml',
    'conda-meta/history',
    'conda-meta/pinned',
    'constraints.txt',
    'deps.clj.edn',
    'deps.cljs.edn',
    'deps.edn',
    'deps.json',
    'deps.kts',
    'dependencies.yml',
    'environment.yaml',
    'environment.yml',
    'go.mod',
    'go.sum',
    'mix.exs',
    'mix.lock',
    'package.json',
    'pom.xml',
    'pyproject.toml',
    'requirements-dev.txt',
    'requirements.in',
    'requirements-prod.txt',
    'requirements.test.txt',
    'requirements.txt',
    'setup.cfg',
    'setup.py',
    'setup.venv.sh',
    'shadow-cljs.edn',
    'snap/snapcraft-deps-lock.yaml',
    'snap/snapcraft-deps.yaml',
    'snap/snapcraft.yaml',
    'snapcraft-deps-lock.yaml',
    'snapcraft-deps.yaml',
    'snapcraft.yaml',
    'tox.ini',
    'yarn.lock',
]
