# Files to ignore when parsing repository contents.

[ignore_files]
ignore_files = [
    # Build artifacts
    "dist",
    "*.egg-info",
    ".eggs",
    ".coverage",
    ".cache",
    ".pytest_cache",
    "htmlcov",
    ".tox",

    # Data files
    "data",
    ".csv",
    ".json",
    ".pickle",
    ".pkl",
    ".sav",
    ".toml",
    ".h5",

    # Documentation
    "docs",
    ".pdf",
    ".docx",
    ".md",

    # Images and media
    "imgs",
    "media",
    "static",
    "assets",
    ".png",
    ".jpg",
    ".gif",
    ".mp4",

    # Configuration files and credentials
    "lock",
    ".env",
    ".env.local",
    ".env.*.local",
    ".env.test",
    ".env.production",
    ".env.example",
    ".config",
    ".cfg",
    ".ini",
    ".yml",
    ".yaml",
    ".xml",
    ".properties",
    ".secret",
    ".key",
    ".pem",
    ".cert",
    ".csr",
    ".p12",

    # Compiled code
    "__init__",
    "__pycache__",
    "*.pyc",
    "*.pyo",
    "*.class",
    "*.o",

    # Version control
    ".git",
    ".svn",
    ".hg",
    ".cvs",

    # Editor and IDE settings
    ".github/workflows",
    ".vscode",
    ".idea",
    "*.sublime-*",
    "*.swp",

    # Test and utility files
    #"test",
    "tests",
    "testing",
    "tools",
    #"utils",
    "requirements",
    "setup",
    "Makefile",
    "MANIFEST",
    "CHANGELOG",
    "README",
    "LICENSE",
    "CONTRIBUTING",
    "CODE_OF_CONDUCT",
    "Dockerfile",
    "Jenkinsfile",
    "Vagrantfile",
]
