# Programming language file extensions and their corresponding names

[language_names]
asm = "Assembly"
c = "C"
cmake = "C"
coffee = "CoffeeScript"
cpp = "CPlusPlus"
cs = "CSharp"
csproj = "CSharp"
dart = "Dart"
fs = "FSharp"
fsi = "FSharp"
go = "Go"
groovy = "Groovy"
h = "C"
hpp = "CPlusPlus"
hs = "Haskell"
html = "HTML"
ipynb = "Jupyter Notebook"
java = "Java"
jl = "Julia"
js = "JavaScript"
json = "JSON"
kt = "Kotlin"
lua = "Lua"
m = "ObjectiveC"
md = "Markdown"
mm = "CPP"
php = "PHP"
pl = "Perl"
ps1 = "PowerShell"
psm1 = "PowerShell"
py = "Python"
r = "R"
rb = "Ruby"
rs = "Rust"
rst = "reStructuredText"
s = "Assembly"
scala = "Scala"
sh = "Shell"
sql = "SQL"
svg = "SVG"
swift = "Swift"
swiftdeps = "Swift"
tex = "TeX"
toml = "TOML"
ts = "TypeScript"
tsx = "TypeScript"
txt = "Text"
v = "Verilog"
vh = "Verilog"
xml = "XML"
yaml = "YAML"
yml = "YAML"
