# Instruction guide for installation and running programming languages

[setup]
ABAP = ["abap build", "abap run"]
ActionScript = ["mxmlc main.as", "flashplayer main.swf"]
Ada = ["gnatmake main.adb", "./main"]
Apex = ["sfdx force:source:deploy -p force-app/main/default", "sfdx force:apex:execute -f main.apex"]
Assembly = ["nasm -f elf64 main.asm && ld main.o -o myapp", "./myapp"]
COBOL = ["cobc -x -o myapp main.cob", "./myapp"]
C = ["gcc -o myapp main.c", "./myapp"]
CPlusPlus = ["g++ -o myapp main.cpp", "./myapp"]
CSharp = ["dotnet build", "dotnet run"]
CoffeeScript = ["npm install", "coffee main.coffee"]
Crystal = ["shards install", "./main"]
D = ["dmd main.d", "./main"]
Dart = ["pub get", "dart main.dart"]
Delphi = ["dcc32 main.dpr", "main.exe"]
Elixir = ["mix deps.get", "mix run main.exs"]
FS = ["dotnet build", "dotnet run"]
Forth = ["gforth main.fs"]
Go = ["go build -o myapp", "./myapp"]
Groovy = ["grape install", "groovy main.groovy"]
Haskell = ["ghc -o myapp main.hs", "./myapp"]
Java = ["mvn clean install", "java -jar target/myapp.jar"]
JavaScript = ["npm install", "npm start"]
Julia = ["julia --project -e 'import Pkg; Pkg.instantiate()'", "julia main.jl"]
Kotlin = ["gradle build", "java -jar build/libs/myapp.jar"]
Lua = ["luarocks install --only-deps myapp", "lua main.lua"]
MATLAB = ["matlab -r main.m"]
Objective-C = ["gcc -framework Foundation main.m -o myapp", "./myapp"]
CPP = ["g++ -o myapp main.mm", "./myapp"]
ObjectScript = ["zpm install", "do ##class(User.MyClass).Main()"]
Perl = ["cpanm --installdeps .", "perl main.pl"]
Perl6 = ["zef install .", "perl6 main.p6"]
PHP = ["composer install", "php main.php"]
PowerShell = ["pwsh main.ps1"]
Prolog = ["swipl -g main -t halt -q main.pl"]
Python = ["pip install -r requirements.txt", "python main.py"]
R = ["Rscript install.R", "Rscript main.R"]
Raku = ["zef install .", "raku main.raku"]
Ruby = ["bundle install", "ruby main.rb"]
Rust = ["cargo build", "cargo run"]
Scala = ["sbt compile", "sbt run"]
Scheme = ["csi -s main.scm"]
Shell = ["chmod +x main.sh", "./main.sh"]
Swift = ["swift build", ".build/debug/myapp"]
TypeScript = ["npm install", "npm run build && node dist/main.js"]
VBScript = ["cscript main.vbs"]
VisualBasic = ["dotnet build", "dotnet run"]
