name: Update README.md via readmeai

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt  # If your tool has any dependencies

    - name: Run Command Line Tool
      run: readmeai -o README.md -k ${{ secrets.OPENAI_API_KEY }} -r ${{ github.repository }}

    - name: Commit changes
      run: |
        git config --local user.email ${{ secrets.GITHUB_ACTOR }}@users.noreply.github.com
        git config --local user.name ${{ secrets.GITHUB_ACTOR }}
        git add README.md
        git commit -m "Update README.md via readmeai." || echo "No changes to commit"
        git push origin main || echo "No changes to push"
